/* eslint-disable no-warning-comments */
/* eslint-disable no-undef */
/* eslint-disable react/jsx-no-bind */
/* eslint-disable react/jsx-no-literals */
/* eslint-disable require-jsdoc */
import React from "react";
import PropTypes from "prop-types";
import { connect } from "react-redux";
import VM from "scratch-vm";
import errorBoundaryHOC from "../../../lib/error-boundary-hoc.jsx";
import { activateTab, BLOCKS_TAB_INDEX } from "../../../reducers/editor-tab";
import Button from "../../../components/button/button.jsx";
import Input from "../../../components/forms/input.jsx";
import styles from "./cloud-storage.css";
import { blobToBase64 } from "../../../lib/save-load-utils";
import { requestNewProject } from "../../../reducers/project-state";
import cpToCbIcon from "./cp-to-cb-icon.png";

import { FormattedMessage, defineMessages, injectIntl } from 'react-intl';

const messages = defineMessages({
  copyToClipboard: {
    id: 'gui.saveLoad.copyToClipboard',
    defaultMessage: 'Copy to Clipboard',
    description: 'Button text to copy the save file code to clipboard'
  },
  copied: {
    id: 'gui.saveLoad.copied',
    defaultMessage: 'Copied!',
    description: 'Message shown when the save file code has been copied to clipboard'
  },
  saveProject: {
    id: 'gui.saveLoad.saveProject',
    defaultMessage: 'Save Project',
    description: 'Button text to save the current project'
  },
  projectSaved: {
    id: 'gui.saveLoad.projectSaved',
    defaultMessage: 'Project saved successfully!',
    description: 'Message shown when the project has been saved successfully'
  },
  projectSaveFailed: {
    id: 'gui.saveLoad.projectSaveFailed',
    defaultMessage: 'Failed to save project',
    description: 'Message shown when the project save fails'
  },
  projectLoaded: {
    id: 'gui.saveLoad.projectLoaded',
    defaultMessage: 'Project loaded successfully!',
    description: 'Message shown when the project has been loaded successfully'
  },
  projectLoadFailed: {
    id: 'gui.saveLoad.projectLoadFailed',
    defaultMessage: 'Failed to load project',
    description: 'Message shown when the project load fails'
  },
  loadProjectPlaceholder: {
    id: 'gui.saveLoad.loadProjectPlaceholder',
    defaultMessage: 'Type the name of the cloud save file you would like to load here...',
    description: 'Placeholder text for the input field to load a project from cloud storage'
  },
  createNewCloudSave: {
    id: 'gui.saveLoad.createNewCloudSave',
    defaultMessage: 'Create a new cloud save file',
    description: 'Title for the section to create a new cloud save file'
  },
  saveFileCode: {
    id: 'gui.saveLoad.saveFileCode',
    defaultMessage: 'Your autogenerated Save File Code is:',
    description: 'Label for the section displaying the autogenerated save file code'
  },
  saveFilePlaceholder: {
    id: 'gui.saveLoad.saveFilePlaceholder',
    defaultMessage: "Your autogenerated Save File Code is:",
    description: 'Placeholder text for the input field to create a new cloud save file'
  }
});

class SaveLoad extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      loadFileName: "",
      isValidFileName: false,
      isLoading: false,
      savedProjectId: "",
      copyToCPText: props.intl.formatMessage(messages.copyToClipboard),
    };
    this.setloadFileName = this.setloadFileName.bind(this);
    this.saveFile = this.saveFile.bind(this);
    this.loadFile = this.loadFile.bind(this);
    this.copyTextToClipboard = this.copyTextToClipboard.bind(this);
    this.fallbackCopyTextToClipboard = this.fallbackCopyTextToClipboard.bind(
      this
    );
  }

  setloadFileName(loadFileName) {
    const isValidFileName = loadFileName.length > 0 && loadFileName.length < 130;
    this.setState({ loadFileName, isValidFileName });
  }

  async saveFile() {
    this.setState((oldState) => {
      return { ...oldState, isLoading: true };
    });
    const sb3Content = await this.props.saveProjectSb3();
    const base64sb3 = await blobToBase64(sb3Content);
    try {
      const savedProjectId = await mv2Interface.saveCloudScratchFile(base64sb3);
      this.setState({ savedProjectId: savedProjectId });
      alert(this.props.intl.formatMessage(messages.projectSaved));
      this.copyTextToClipboard(savedProjectId);
    } catch (error) {
      alert(this.props.intl.formatMessage(messages.projectSaveFailed));
    }
    this.setState((oldState) => {
      return { ...oldState, isLoading: false };
    });
  }

  async loadFile(fileName) {
    const { vm } = this.props;

    if (!vm.editingTarget) {
      return null;
    }

    let projectId = fileName;
    if (this.validURL(fileName)) {
      if (!fileName.includes("http")) fileName = "https://" + fileName;
      const url = new URL(fileName);
      projectId = url.searchParams.get('p') || "";
    }

    this.setState((oldState) => {
      return { ...oldState, isLoading: true };
    });
    try {
      const base64Project = await mv2Interface.loadCloudScratchFile(projectId);
      if (!base64Project) throw new Error("Couldn't find project with id: " + projectId);
      const blob = await fetch(base64Project);
      const arrayBuffer = await blob.arrayBuffer();
      vm.loadProject(arrayBuffer);
      alert(this.props.intl.formatMessage(messages.projectLoaded));
      setTimeout(() => {
        // give some time so all the buttons/devices are rendered before we start updating the UI
        window.raftManager.onProjectLoaded();
      }, 2000);
      // this seems to be required to let the wm load the project
      window.setTimeout(() => this.props.onActivateBlocksTab());
    } catch (error) {
      alert(this.props.intl.formatMessage(messages.projectLoadFailed));
    }
    this.setState((oldState) => {
      return { ...oldState, isLoading: false };
    });
  }

  fallbackCopyTextToClipboard(text) {
    var textArea = document.createElement("textarea");
    textArea.value = text;

    // Avoid scrolling to bottom
    textArea.style.top = "0";
    textArea.style.left = "0";
    textArea.style.position = "fixed";

    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();

    try {
      var successful = document.execCommand("copy");
      var msg = successful ? "successful" : "unsuccessful";
      setTimeout(() => {
        this.setState({ copyToCPText: this.props.intl.formatMessage(messages.copyToClipboard) });
      }, 3000);
      this.setState({ copyToCPText: this.props.intl.formatMessage(messages.copied) });
      console.log("Fallback: Copying text command was " + msg);
    } catch (err) {
      console.error("Fallback: Oops, unable to copy", err);
    }

    document.body.removeChild(textArea);
  }
  copyTextToClipboard(text) {
    if (!navigator.clipboard) {
      this.fallbackCopyTextToClipboard(text);
      return;
    }
    navigator.clipboard.writeText(text).then(
      () => {
        setTimeout(() => {
          this.setState({ copyToCPText: this.props.intl.formatMessage(messages.copyToClipboard) });
        }, 3000);
        this.setState({ copyToCPText: this.props.intl.formatMessage(messages.copied) });
        console.log("Async: Copying to clipboard was successful!");
      },
      (err) => {
        console.error("Async: Could not copy text: ", err);
      }
    );
  }

  validURL(str) {
    var pattern = new RegExp('^(https?:\\/\\/)?' + // protocol
      '((([a-z\\d]([a-z\\d-]*[a-z\\d])*)\\.)+[a-z]{2,}|' + // domain name
      '((\\d{1,3}\\.){3}\\d{1,3}))' + // OR ip (v4) address
      '(\\:\\d+)?(\\/[-a-z\\d%_.~+]*)*' + // port and path
      '(\\?[;&a-z\\d%_.~+=-]*)?' + // query string
      '(\\#[-a-z\\d_]*)?$', 'i'); // fragment locator
    return !!pattern.test(str);
  }

  render() {
    const { loadFileName, isValidFileName } = this.state;
    return (
      <div className={styles.mainContent}>
        <div className={styles.block}>
          <div className={styles.loadProjectContainer}>
            <div className={styles.loadProjectTitle}>
              <FormattedMessage
                id="gui.saveLoad.loadProjectTitle"
                defaultMessage="Load a cloud save"
                description="Title for the load project section"
              />
            </div>
            <Input
              style={{ flex: 1, marginLeft: 10 }}
              type="text"
              placeholder={this.props.intl.formatMessage(messages.loadProjectPlaceholder)}
              value={loadFileName}
              onChange={(event) =>
                this.setloadFileName(event.currentTarget.value)
              }
            />
            <Button
              style={{
                marginLeft: 10,
                marginRight: 5,
                opacity: isValidFileName ? 1 : 0.2,
              }}
              className={styles.button}
              disabled={!isValidFileName}
              onClick={() => this.loadFile(loadFileName)}
            >
              <FormattedMessage
                id="gui.saveLoad.loadFile"
                defaultMessage="Load Project"
                description="Button text to load a project from cloud storage"
              />
            </Button>
          </div>
          <div
            className={styles.loadProjectContainer}
            style={{ marginTop: "1rem" }}
          >
            <div className={styles.loadProjectTitle}>
              {this.props.intl.formatMessage(messages.createNewCloudSave)}
            </div>
            <Button
              style={{
                marginLeft: 10,
                marginRight: 5,
                opacity: !this.state.isLoading ? 1 : 0.2,
              }}
              disabled={this.state.isLoading}
              className={styles.button}
              onClick={() => this.saveFile()}
            >
              <FormattedMessage
                id="gui.saveLoad.saveFile"
                defaultMessage="Save Project"
                description="Button text to save the current project to cloud storage"
              />
            </Button>
            <Input
              style={{ flex: 1, marginLeft: 10 }}
              type="text"
              placeholder={this.props.intl.formatMessage(messages.saveFilePlaceholder)}
              value={this.state.savedProjectId}
              editable="false"
            />
            <Button
              iconSrc={cpToCbIcon}
              style={{
                marginLeft: 10,
                marginRight: 5,
                opacity: !!this.state.savedProjectId ? 1 : 0.2,
              }}
              className={styles.button}
              disabled={!!!this.state.savedProjectId}
              onClick={() =>
                this.copyTextToClipboard(this.state.savedProjectId)
              }
            >
              {this.state.copyToCPText}
            </Button>
          </div>
        </div>
        {this.state.isLoading && (
          <div className={styles.ldsSpinner}>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
          </div>
        )}
        <div
          className={[styles.block, styles["block-100"]].join(" ")}
          style={{ marginTop: "2rem" }}
        >
          <div className={styles.tipsContainer}>
            <div className={styles.tipsTitle}><FormattedMessage
              id="gui.saveLoad.tipsTitle"
              defaultMessage="Tips for Cloud Saving:"
              description="Title for the tips section for cloud saving"
            />
            </div>
            <ul className={styles.tipsList}>
              <li>
                <FormattedMessage
                  id="gui.saveLoad.tips1"
                  defaultMessage="Make sure to write down or record the auto-generated code that is provided each time you save a new file. You will need this to load it in the future."
                  description="Tip for cloud saving"
                />
              </li>
              <li>
                <FormattedMessage
                  id="gui.saveLoad.tips2"
                  defaultMessage="Although the Marty the Robot app will continue to auto-save files to the local space storage, there is no auto-save function for cloud save files. Please manually re-save your file each time, if you wish them to be available for download over cloud storage."
                  description="Tip for cloud saving"
                />
              </li>
              <li>
                <FormattedMessage
                  id="gui.saveLoad.tips3"
                  defaultMessage="Each time you re-save a file to cloud storage, you will be provided with a NEW SAVE FILE CODE. Please take a note of this."
                  description="Tip for cloud saving"
                />
              </li>
            </ul>
          </div>
        </div>
      </div>
    );
  }
}

SaveLoad.propTypes = {
  onActivateBlocksTab: PropTypes.func,
  saveProjectSb3: PropTypes.func,
  editingTarget: PropTypes.string,
  locale: PropTypes.string.isRequired,
  onProjectTelemetryEvent: PropTypes.func,
  projectTitle: PropTypes.string,
  vm: PropTypes.instanceOf(VM).isRequired,
  onConfirmNewProject: PropTypes.func,
};

const mapStateToProps = (state) => ({
  editingTarget: state.scratchGui.targets.editingTarget,
  locale: state.locales.locale,
  saveProjectSb3: state.scratchGui.vm.saveProjectSb3.bind(state.scratchGui.vm),
});

const mapDispatchToProps = (dispatch) => ({
  onActivateBlocksTab: () => dispatch(activateTab(BLOCKS_TAB_INDEX)),
  onConfirmNewProject: () => dispatch(requestNewProject(false)),
});

export default errorBoundaryHOC("Save / Load")(
  injectIntl(connect(mapStateToProps, mapDispatchToProps)(SaveLoad))
);
