name: BuildMartyBlocks
on: [workflow_dispatch]
jobs:
  build_martyblocks_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v1
      - name: Build MartyBlocks using Docker Image
        uses: docker/build-push-action@v2
        id: build-martyblocks
        with:
          tags: user/app:latest
          push: false
          load: true
          # builder: ${{ steps.buildx.outputs.name }}
      # - uses: shrink/actions-docker-extract@v1
      #   id: extract
      #   with:
      #     image: martyblocks-image
      #     path: /MartyBlocks/scratch-gui/build.
      # - name: Upload Dist
      #   uses: actions/upload-artifact@v2
      #   with:
      #     path: ${{ steps.extract.outputs.destination }}
      #     name: dist
