name: Build and publish to npm

on:
  push:
    branches:
      - 'master'

jobs:
  build_and_release:
    runs-on: ubuntu-20.04

    env:
      NODE_OPTIONS: "--max-old-space-size=5120" # locally export NODE_OPTIONS=--max-old-space-size=5120
      MBHome: /home/runner/work/MartyBlocks/MartyBlocks
      mblib: /home/runner/work/MartyBlocks/MartyBlocks/marty-blocks-lib/
      REPLACEMENTS: /home/runner/work/MartyBlocks/MartyBlocks/marty-blocks-lib/replacements
      blocks_original: /home/runner/work/MartyBlocks/MartyBlocks/scratch-blocks

    steps:

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch || 'master' }}

      - name: Set up Python 2.7
        run: |
          sudo apt-get update
          sudo apt-get install python2.7

      - name: Link python to python2.7
        run: |
          sudo ln -sf /usr/bin/python2.7 /usr/bin/python
          
      - name: Use Node.js 16.20.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.1

      - name: see node version
        run: node -v

      - name: see memory allocation
        run: node -e 'console.log(`node heap limit = ${require("v8").getHeapStatistics().heap_size_limit / (1024 * 1024)} Mb`)'

      - name: Clone repos
        run: |
          git clone -b develop https://github.com/llk/scratch-blocks.git --no-checkout ${{ env.blocks_original }}

      - name: Checkout appropriate commit
        run: |
          cd ${{ env.blocks_original }} && git reset --hard f210e042988b91bcdc2abeca7a2d85e178edadb2

      - name: Install scratch
        run: |
          cd ${{ env.blocks_original }} && npm install 

      - name: Install marty blocks library
        run: |
          cd ${{ env.mblib }}
          npm install

      - name: setting production environments
        run: |
          cd ${{ env.mblib }}
          npx node set-production.js

      - name: Link repositories
        run: |
          cd ${{ env.mblib }} && npm link
          cd ${{ env.blocks_original }} && npm link && npm link marty-blocks-lib

      - name: check if scracth-blocks linking worked
        run: |
          cd ${{ env.blocks_original }}
          npm list || true

      - name: Copy replacements
        run: |
          cp -r ${{ env.REPLACEMENTS }}/* ${{ env.MBHome }}

      - name: console
        run: |
          cd ${{ env.blocks_original }}
          npx uglify-js --version

      - name: console 1
        run: |
          cd ${{ env.blocks_original }}
          npm ls uglify-js

      - name: Build Blocks
        run: |
          cd ${{ env.blocks_original }}
          NODE_ENV=production npm run prepublish