name: BuildMartyBlocks
on: [workflow_dispatch]


jobs:
  setup_project:
    runs-on: ubuntu-latest
    env:
      MBHome: .
      mblib: ./marty-blocks-lib/
      REPLACEMENTS: ./marty-blocks-lib/replacements
      blocks_original: ./scratch-blocks
      vm_original: ./scratch-vm
      gui_original: ./scratch-gui

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          path: .

      - uses: actions/setup-python@v4
        with:
          python-version: '2.7.18' 

      - name: Clone repos with cache
        id: clone_repos
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.blocks_original }}
            ${{ env.vm_original }}
            ${{ env.gui_original }}
          key: "${{ env.blocks_original }}-${{ env.vm_original }}-${{ env.gui_original }}-v1"
        run: |
          git clone -b develop https://github.com/llk/scratch-blocks.git ${{ env.blocks_original }}
          git clone -b develop https://github.com/llk/scratch-vm.git ${{ env.vm_original }}
          git clone -b develop https://github.com/llk/scratch-gui.git ${{ env.gui_original }}


      - name: Checkout appropriate commit
        run: |
          cd ${{ env.blocks_original }} && git reset --hard f9107bf5d0479d632658f2b203995f5ae6d75363
          cd ${{ env.vm_original }} && git reset --hard 3b36a8e3ea7f3caa5b4bf4ae7b4f821a986a1378
          cd ${{ env.gui_original }} && git reset --hard 738c86bb58e336711280aec33c510d7aef79408e

      # - name: Install scratch
      #   run: |
      #     cd ${{ env.blocks_original }} && npm install 
      #     cd ${{ env.vm_original }} && npm install 
      #     cd ${{ env.gui_original }} && npm install
      - name: Install scratch-blocks dependencies
        run: |
          cd ${{ env.blocks_original }} && npm install
        env:
          cache-paths: |
            node_modules/
        id: npm_install_blocks

      - name: Restore scratch-blocks dependencies cache
        if: steps.npm_install_blocks.outputs.cache-hit != 'true'
        env:
          cache-paths: |
            node_modules/
        id: restore_cache_blocks
        uses: actions/cache@v2

      - name: Save scratch-blocks dependencies cache
        if: steps.npm_install_blocks.outputs.cache-hit == 'true'
        env:
          cache-paths: |
            node_modules/
        id: save_cache_blocks
        uses: actions/cache@v2


      - name: Install scratch_vm dependencies
        run: |
          cd ${{ env.vm_original }} && npm install
        env:
          cache-paths: |
            node_modules/
        id: npm_install_blocks

      - name: Restore scratch_vm dependencies cache
        if: steps.npm_install_blocks.outputs.cache-hit != 'true'
        env:
          cache-paths: |
            node_modules/
        id: restore_cache_blocks
        uses: actions/cache@v2

      - name: Save scratch_vm dependencies cache
        if: steps.npm_install_blocks.outputs.cache-hit == 'true'
        env:
          cache-paths: |
            node_modules/
        id: save_cache_blocks
        uses: actions/cache@v2


      - name: Install scratch-gui dependencies
        run: |
          cd ${{ env.gui_original }} && npm install
        env:
          cache-paths: |
            node_modules/
        id: npm_install_blocks

      - name: Restore scratch-gui dependencies cache
        if: steps.npm_install_blocks.outputs.cache-hit != 'true'
        env:
          cache-paths: |
            node_modules/
        id: restore_cache_blocks
        uses: actions/cache@v2

      - name: Save scratch-gui dependencies cache
        if: steps.npm_install_blocks.outputs.cache-hit == 'true'
        env:
          cache-paths: |
            node_modules/
        id: save_cache_blocks
        uses: actions/cache@v2



      - name: Install marty-lib dependencies
        run: |
          cd ${{ env.mblib }} && npm install
        env:
          cache-paths: |
            node_modules/
        id: npm_install_blocks

      - name: Restore marty-lib dependencies cache
        if: steps.npm_install_blocks.outputs.cache-hit != 'true'
        env:
          cache-paths: |
            node_modules/
        id: restore_cache_blocks
        uses: actions/cache@v2

      - name: Save marty-lib dependencies cache
        if: steps.npm_install_blocks.outputs.cache-hit == 'true'
        env:
          cache-paths: |
            node_modules/
        id: save_cache_blocks
        uses: actions/cache@v2

      - name: Link repositories
        run: |
          cd ${{ env.mblib }} && npm link
          cd ${{ env.blocks_original }} && npm link && npm link marty-blocks-lib
          cd ${{ env.vm_original }} && npm link && npm link marty-blocks-lib scratch-blocks
          cd ${{ env.gui_original }} && npm link marty-blocks-lib scratch-blocks scratch-vm

      - name: Copy replacements
        run: |
          cp -r ${{ env.REPLACEMENTS }}/* ${{ env.MBHome }}

      - name: Build Scratch
        run: |
          cd ${{ env.gui_original }}
          BUILD_MODE=dist npm run build

      - name: delete me
        run: |
          cd ${{ env.gui_original }}
          ls -l

      - name: Copy dist files
        run: |
          cp -r ${{ env.gui_original }}/dist ${{ env.MBHome }}

      - name: delete me 2
        run: |
          cd ${{ env.MBHome }}
          ls -l
          ls dist

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
